### ISSUE TITLE
提个BUG：push个数有点多的时候内部报错

### ISSUE THREAD

**Issue by YdjJervis** [zhegexiaohuozi/SeimiAgent#10]
java.lang.NullPointerException: null
	at java.security.MessageDigest.update(MessageDigest.java:323) ~[na:1.7.0_79]
	at java.security.MessageDigest.digest(MessageDigest.java:398) ~[na:1.7.0_79]
	at org.apache.commons.codec.digest.DigestUtils.md5(DigestUtils.java:165) ~[commons-codec-1.6.jar:1.6]
	at org.apache.commons.codec.digest.DigestUtils.md5(DigestUtils.java:190) ~[commons-codec-1.6.jar:1.6]
	at org.apache.commons.codec.digest.DigestUtils.md5Hex(DigestUtils.java:226) ~[commons-codec-1.6.jar:1.6]
	at cn.wanghaomiao.seimi.def.DefaultLocalQueue.isProcessed(DefaultLocalQueue.java:71) ~[classes/:na]
	at cn.wanghaomiao.seimi.core.SeimiProcessor.run(SeimiProcessor.java:92) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]

希望BaseSeimiCrawler能设置线程数，谢谢查看

**Comment by zhegexiaohuozi** [comment]
`SeimiCrawler`相关问题请到https://github.com/zhegexiaohuozi/SeimiCrawler/issues
