### ISSUE TITLE
只要一使用UA就报错，求大神指导

### ISSUE THREAD

**Issue by YdjJervis** [zhegexiaohuozi/SeimiAgent#9]
10:01:54 ERROR c.w.seimi.core.SeimiProcessor - timeout
java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:212) ~[okio-1.8.0.jar:na]
	at okio.AsyncTimeout.exit(AsyncTimeout.java:288) ~[okio-1.8.0.jar:na]
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:242) ~[okio-1.8.0.jar:na]
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325) ~[okio-1.8.0.jar:na]
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314) ~[okio-1.8.0.jar:na]
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210) ~[okio-1.8.0.jar:na]
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184) ~[okhttp-3.3.1.jar:na]
	at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125) ~[okhttp-3.3.1.jar:na]
	at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:775) ~[okhttp-3.3.1.jar:na]
	at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:86) ~[okhttp-3.3.1.jar:na]
	at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:760) ~[okhttp-3.3.1.jar:na]
	at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:613) ~[okhttp-3.3.1.jar:na]
	at okhttp3.RealCall.getResponse(RealCall.java:244) ~[okhttp-3.3.1.jar:na]
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201) ~[okhttp-3.3.1.jar:na]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163) ~[okhttp-3.3.1.jar:na]
	at okhttp3.RealCall.execute(RealCall.java:57) ~[okhttp-3.3.1.jar:na]
	at cn.wanghaomiao.seimi.http.okhttp.OkHttpDownloader.process(OkHttpDownloader.java:74) ~[classes/:na]
	at cn.wanghaomiao.seimi.core.SeimiProcessor.run(SeimiProcessor.java:106) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:190) ~[na:1.7.0_79]
	at java.net.SocketInputStream.read(SocketInputStream.java:122) ~[na:1.7.0_79]
	at okio.Okio$2.read(Okio.java:140) ~[okio-1.8.0.jar:na]
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:238) ~[okio-1.8.0.jar:na]
	... 18 common frames omitted
10:01:54 INFO  c.w.seimi.core.SeimiProcessor - Request process error,req will go into queue again,url=http://www.bjstats.gov.cn/tjsj/yjdsj/GDP/2015,maxReqCount=3,currentReqCount=1

**Comment by zhegexiaohuozi** [comment]
`SeimiCrawler`相关问题请移步https://github.com/zhegexiaohuozi/SeimiCrawler/issues，同时说明如何复现，关于UA官方用例都是没有问题的，无法复现你的场景。
